config/routes.rb
BBTangCMS::Application.routes.draw do

  namespace :admin do
    resources :base_settings, :include => [:index] do
      collection do
        match 'save'
        match 'add_report_reason'
        match 'delete_report_reason'
      end
    end

    resources :email_settings, :include => [:index] do
      collection do
        match 'save'
        match 'send_test_email'
      end
    end

    resources :code_settings

    resources :links_settings, :include => [:index] do
      collection do
        match 'new_link'
        match 'create_link'
        match 'edit_link'
        match 'update_link'
        match 'delete_link'
      end
    end

    resources :seo_settings

    resources :ip_settings do
      collection do
        post :save
      end
    end

  end

  resources :attachments

  namespace :auth do
    resources :users
    resources :cms_roles
    resources :assign_permits
    root :to => 'dashboard#show', :as => :dashboard
  end

  resources :messages, :only => [:new, :create] do
    collection do
      get 'token' => 'messages#token', :as => 'token'
      post 'empty/:messagebox' => 'messages#empty', :as => 'empty'
      put 'update' => 'messages#update'
      get ':messagebox/show/:id' => 'messages#show', :as => 'show', :constraints => { :messagebox => /inbox|outbox|trash/ }
      get '(/:messagebox)' => 'messages#index', :as => 'box', :constraints => { :messagebox => /inbox|outbox|trash/ }
    end
  end

  resources :notes, :except => [:new, :create]

  namespace :kindeditor do
    match '/upload' => 'assets#create', :via => :post
    match '/filemanager' => 'assets#list', :via => :get
  end

  resources :knowledges do
    member do
      get 'refresh'
    end
  end

  resources :profiles, :except => [:new, :create]
  resources :page_requests

  resources :questions do
    collection do
      get 'resetscore'
      match 'update_timelines'
      match 'update_categories'
    end
    resources :answers
  end

  namespace :quiz_center do
    resources :quizzes
    resources :quiz_collections
    root :to => 'quiz_collections#index', :as => :dashboard
  end

  namespace :recommend do
    resources :expert_categories
    resources :other_columns
    resources :recommend_apps
    resources :recommend_events
    resources :recommend_hindices
    resources :recommend_mtools
    resources :recommend_others do
      collection do
        match 'update_field'
      end
    end
    resources :recommend_quizzes
    resources :recommend_products
    resources :recommend_ptags
    resources :recommend_questions
    resources :recommend_subjects
    resources :recommend_tags
    resources :recommend_users
    resources :vip_categories
    root :to => 'dashboard#show', :as => :dashboard
  end
  
  resources :source_trackers do
    collection do
      match :query
    end
  end

  get "site/about"
  get "site/changelog"
  get "site/license"
  get "site/policies"
  get "site/team"
  get "site/support"

  namespace :tag do
    resources :identities , :only => [:index, :show, :new, :create] do
      resources :timelines, :only => [:index, :show, :new, :create] do
        resources :categories
      end
    end
    root :to => 'dashboard#show', :as => :dashboard
  end

  namespace :work do
    resources :analytics, only: [:index ] do
      collection do
        match :filter
      end
    end
    resources :versions, only: [:index, :show ]
    resources :user_statistics, only: [:index ] do
      collection do
        match :filter
      end
    end
    resources :contacts
    root :to => 'dashboard#show', :as => :dashboard
  end

  devise_for :users

  match "common/search", :as => :common_search
  match "common/lastest_log", :as => :common_lastest_log
  root :to => 'dashboard#index'
  match "/archives/hot_tags/" => "hot_tags#index", :as => :hot_tags, :via => :get
  match "/archives/:model/" => "archives#index", :as => :archives, :via => :get
  match "/archives/savesort" => 'archives#savesort'
  match "/archives/search_tag" => 'archives#search_tag', :as => :search_tag
  match '/archives/:model/item_list/:item_id/' => "archives#item_list", :as => :archive_item_list, :via => :get

  unless BBTangCMS::Application.config.consider_all_requests_local
    match '/403', :to => 'errors#render_403'
    match '/404', :to => 'errors#render_404'
    match '/422', :to => 'errors#render_422'
    match '/500', :to => 'errors#render_500'
  end

end

app/models/recommend/expert_category.rb
# encoding: utf-8
=begin
rails g mongoid:model recommend/vip_category name:string sort_index:integer
Recommend::ExpertCategory
  init with some date special gave
  expert_category
    name
    sort_index (limit count), per must uniq value in (1 .. count)  count(default is 5) set by code
    timestamps

  can crud by special  user

profile.expert_category_list
  user can only check some expert_category gave
    can select within
      if profile.expert_categories.present?
        profile.expert_categories.map(&:name).concat(Recommend::ExpertCategory.all.entries.map(&:name))
      else
        Recommend::ExpertCategory.all.map(&:name)
      end
=end
class Recommend::ExpertCategory
  include Mongoid::Document
  #include Mongoid::Timestamps::Created
  include Mongoid::Timestamps

  validates_uniqueness_of :sort_index,:allow_nil => true,:allow_blank => true
  validates :sort_index, numericality: { :only_integer => true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5 },:allow_nil => true,:allow_blank => true
  #validates :sort_index, uniqueness: true
  validates_uniqueness_of :name, :presence => true


  field :name, type: String
  field :sort_index, type: Integer



  def to_s
    "#{self.name}" if self.name.present?
  end
end

app/models/recommend/other_column.rb
# encoding: utf-8
class Recommend::OtherColumn
  include Mongoid::Document
  #include Mongoid::Timestamps::Created
  include Mongoid::Timestamps
  before_validation :set_array


  field :recommend_type, type: String
  #field :other_column_hash, type: Array#[human_name , colmun_name]
  field :human_names, type: Array #[human_name1 , human_name2, human_name3]
  field :column_names, type: Array #[colmun_name1 , colmun_name2, colmun_name3]

  validates :recommend_type, :column_names, :presence => true
  validates_uniqueness_of :recommend_type


  def set_array
    self.human_names = convert_array(self.human_names)
    self.column_names = convert_array(self.column_names)
  end

  def convert_array(str=nil)
    if str.present?
     str = str.to_s.split(/，|,|;|；|\ +|\||\r\n/).collect {|t| t if t.present?}.uniq.compact
    else
      []
    end
  end

=begin
  def dynamic_attributes
    self.attributes.delete_if { |attribute|
      self.fields.keys.member? attribute
    }
  end
=end
end

app/controllers/recommend/expert_categories_controller.rb
class Recommend::ExpertCategoriesController < Recommend::RecommendBaseController
  load_and_authorize_resource  :class =>"Recommend::ExpertCategory"
  Model_class = Recommend::ExpertCategory.new.class
  # GET /recommend/expert_categories
  # GET /recommend/expert_categories.json
  def index
    @recommend_expert_categories = Recommend::ExpertCategory.desc(:sort_index).paginate(:page => params[:page])
    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), recommend_expert_categories_path

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recommend_expert_categories }
    end
  end

  # GET /recommend/expert_categories/1
  # GET /recommend/expert_categories/1.json
  def show
    @recommend_expert_category = Recommend::ExpertCategory.find(params[:id])
    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), recommend_expert_category_path(@recommend_expert_category)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recommend_expert_category }
    end
  end

  # GET /recommend/expert_categories/new
  # GET /recommend/expert_categories/new.json
  def new
    @recommend_expert_category = Recommend::ExpertCategory.new
    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), new_recommend_expert_category_path

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recommend_expert_category }
    end
  end

  # GET /recommend/expert_categories/1/edit
  def edit
    @recommend_expert_category = Recommend::ExpertCategory.find(params[:id])

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), edit_recommend_expert_category_path(@recommend_expert_category)
  end

  # POST /recommend/expert_categories
  # POST /recommend/expert_categories.json
  def create
    @recommend_expert_category = Recommend::ExpertCategory.new(params[:recommend_expert_category])

    respond_to do |format|
      if @recommend_expert_category.save
        format.html { redirect_to @recommend_expert_category, notice: 'Expert category was successfully created.' }
        format.json { render json: @recommend_expert_category, status: :created, location: @recommend_expert_category }
      else
        format.html { render action: "new" }
        format.json { render json: @recommend_expert_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recommend/expert_categories/1
  # PUT /recommend/expert_categories/1.json
  def update
    @recommend_expert_category = Recommend::ExpertCategory.find(params[:id])

    respond_to do |format|
      if @recommend_expert_category.update_attributes(params[:recommend_expert_category])
        format.html { redirect_to @recommend_expert_category, notice: 'Expert category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recommend_expert_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommend/expert_categories/1
  # DELETE /recommend/expert_categories/1.json
  def destroy
    @recommend_expert_category = Recommend::ExpertCategory.find(params[:id])
    @recommend_expert_category.destroy

    respond_to do |format|
      format.html { redirect_to recommend_expert_categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/recommend/other_columns_controller.rb
class Recommend::OtherColumnsController < Recommend::RecommendBaseController
  load_and_authorize_resource  :class =>"Recommend::OtherColumn"
  Model_class = Recommend::OtherColumn.new.class
  # GET /recommend/other_columns
  # GET /recommend/other_columns.json
  def index
    @recommend_other_columns = Recommend::OtherColumn.paginate(:page => params[:page])
    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), recommend_other_columns_path

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recommend_other_columns }
    end
  end

  # GET /recommend/other_columns/1
  # GET /recommend/other_columns/1.json
  def show
    @recommend_other_column = Recommend::OtherColumn.find(params[:id])

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), recommend_other_column_path(@recommend_other_column)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recommend_other_column }
    end
  end

  # GET /recommend/other_columns/new
  # GET /recommend/other_columns/new.json
  def new
    @recommend_other_column = Recommend::OtherColumn.new

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), new_recommend_other_column_path

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recommend_other_column }
    end
  end

  # GET /recommend/other_columns/1/edit
  def edit
    @recommend_other_column = Recommend::OtherColumn.find(params[:id])

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), edit_recommend_other_column_path(@recommend_other_column)
  end

  # POST /recommend/other_columns
  # POST /recommend/other_columns.json
  def create
    @recommend_other_column = Recommend::OtherColumn.new(params[:recommend_other_column])

    respond_to do |format|
      if @recommend_other_column.save
        format.html { redirect_to @recommend_other_column, notice: 'Other column was successfully created.' }
        format.json { render json: @recommend_other_column, status: :created, location: @recommend_other_column }
      else
        format.html { render action: "new" }
        format.json { render json: @recommend_other_column.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recommend/other_columns/1
  # PUT /recommend/other_columns/1.json
  def update
    @recommend_other_column = Recommend::OtherColumn.find(params[:id])

    respond_to do |format|
      if @recommend_other_column.update_attributes(params[:recommend_other_column])
        format.html { redirect_to @recommend_other_column, notice: 'Other column was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recommend_other_column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommend/other_columns/1
  # DELETE /recommend/other_columns/1.json
  def destroy
    @recommend_other_column = Recommend::OtherColumn.find(params[:id])
    @recommend_other_column.destroy

    respond_to do |format|
      format.html { redirect_to recommend_other_columns_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/recommend/recommend_apps_controller.rb
class Recommend::RecommendAppsController < Recommend::RecommendBaseController
  load_and_authorize_resource :class =>"Recommend::RecommendApp"
  Model_class = Recommend::RecommendApp.new.class
  # GET /recommend/recommend_apps
  # GET /recommend/recommend_apps.json
  def index
    @recommend_recommend_apps = Recommend::RecommendApp.paginate(:page => params[:page])
    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), recommend_recommend_apps_path

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recommend_recommend_apps }
    end
  end

  # GET /recommend/recommend_apps/1
  # GET /recommend/recommend_apps/1.json
  def show
    @recommend_recommend_app = Recommend::RecommendApp.find(params[:id])

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), recommend_recommend_app_path(@recommend_recommend_app)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recommend_recommend_app }
    end
  end

  # GET /recommend/recommend_apps/new
  # GET /recommend/recommend_apps/new.json
  def new
    @recommend_recommend_app = Recommend::RecommendApp.new

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), new_recommend_recommend_app_path

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recommend_recommend_app }
    end
  end

  # GET /recommend/recommend_apps/1/edit
  def edit
    @recommend_recommend_app = Recommend::RecommendApp.find(params[:id])

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), edit_recommend_recommend_app_path(@recommend_recommend_app)
  end

  # POST /recommend/recommend_apps
  # POST /recommend/recommend_apps.json
  def create
    @recommend_recommend_app = Recommend::RecommendApp.new(params[:recommend_recommend_app])

    respond_to do |format|
      if @recommend_recommend_app.save
        format.html { redirect_to @recommend_recommend_app, notice: 'Recommend app was successfully created.' }
        format.json { render json: @recommend_recommend_app, status: :created, location: @recommend_recommend_app }
      else
        format.html { render action: "new" }
        format.json { render json: @recommend_recommend_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recommend/recommend_apps/1
  # PUT /recommend/recommend_apps/1.json
  def update
    @recommend_recommend_app = Recommend::RecommendApp.find(params[:id])

    respond_to do |format|
      if @recommend_recommend_app.update_attributes(params[:recommend_recommend_app])
        format.html { redirect_to @recommend_recommend_app, notice: 'Recommend app was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recommend_recommend_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommend/recommend_apps/1
  # DELETE /recommend/recommend_apps/1.json
  def destroy
    @recommend_recommend_app = Recommend::RecommendApp.find(params[:id])
    @recommend_recommend_app.destroy

    respond_to do |format|
      format.html { redirect_to recommend_recommend_apps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/recommend/recommend_base_controller.rb
class Recommend::RecommendBaseController < ApplicationController
  after_filter :add_initial_breadcrumbs


  #before_filter :require_login
  protected

  def require_login
    return redirect_to(admin_session_path) unless session[:logged_in]
  end

  def set_content_type
    headers['Content-Type'] ||= 'text/html; charset=utf-8'
  end
  private
  def add_initial_breadcrumbs
    breadcrumbs.add :homepage, root_path
    breadcrumbs.add ".namespace.recommend", recommend_dashboard_path
  end
end

app/views/recommend/recommend_others/_form.html.erb
<%= simple_form_for(@recommend_recommend_other, :html => {id: "recommend_recommend_other"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :_id, as: :hidden %>
    <%= f.input :recommend_other_type, as: :select, collection: Recommend::OtherColumn.all.map(&:recommend_type) %>
    <%= f.input :description, as: :text, :input_html => { :rows =>"5", :cols =>"80" } %>
    <%# f.input :created_at %>
    <%# f.input :updated_at %>
    <% dynamic_feilds = @recommend_recommend_other.dynamic_attribute_names %>
    <% if dynamic_feilds.present? %>
      <% dynamic_feilds.each do |dynamic_feild|%>
        <%= f.input dynamic_feild, :as => :text, :label => "#{@recommend_recommend_other.dynamic_attribute_human(dynamic_feild)}", :input_html => { :rows =>"5", :cols =>"80" }  %>
      <% end %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary', :disable_with => 'loading...' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                recommend_recommend_others_path, :class => 'btn' %>
  </div>
<% end %>

app/views/recommend/recommend_others/edit.html.erb
<%- model_class = Recommend::RecommendOther.new.class -%>
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Editing #{model_class.model_name.human}") %></h1>

<%= render 'form' %>

app/views/recommend/recommend_others/index.html.erb
<%- model_class = Recommend::RecommendOther.new.class -%>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>

<div class = "recommend_recommend_others box">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:recommend_other_type) %></th>
        <th><%= model_class.human_attribute_name(:description) %></th>
        <th><%= model_class.human_attribute_name(:field) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%= model_class.human_attribute_name(:updated_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <%- indicates = true %>
        <% @recommend_recommend_others.each do |recommend_recommend_other| %>
          <tr>
            <td><%= recommend_recommend_other.recommend_other_type %></td>
            <td><%= truncate recommend_recommend_other.description, length: 60 %></td>
            <td><%= recommend_recommend_other.dynamic_attribute_names %></td>
          <td><%= time_tag(recommend_recommend_other.created_at, :format => :short) if recommend_recommend_other.created_at?%></td>
          <td><%= timeago_tag(recommend_recommend_other.updated_at, :format => :short) if recommend_recommend_other.updated_at?%></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show", :model => model_class.model_name.human)), recommend_recommend_other, :class => 'btn btn-mini' %>
            <% if can? :update, recommend_recommend_other %>
              <%= link_to t('.edit', :default => t("helpers.links.edit", :model => model_class.model_name.human)), edit_recommend_recommend_other_path(recommend_recommend_other), :class => 'btn btn-mini' %>
            <% end %>
            <% if can? :destroy, recommend_recommend_other %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy", :model => model_class.model_name.human)), recommend_recommend_other, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate  @recommend_recommend_others %>
  <br />
  <% if can? :create, Recommend::RecommendOther %>
    <%= link_to t('.new', :default => t("helpers.links.new", :model => model_class.model_name.human)), new_recommend_recommend_other_path %>
  <% end %>
</div>

app/views/recommend/recommend_others/new.html.erb
<%- model_class = Recommend::RecommendOther.new.class -%>
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
<%= render 'form' %>

app/views/recommend/recommend_others/show.html.erb
<%- model_class = Recommend::RecommendOther.new.class -%>
  <h1><%=t '.title', :default => t('helpers.titles.show', :model => model_class.model_name.human,
                                 :default => "Show #{model_class.model_name.human}") %></h1>
<%= show_for @recommend_recommend_other do |s| %>
  <%= s.attribute :recommend_other_type %>
  <%= s.attribute :description %>
  <% dynamic_feilds = @recommend_recommend_other.dynamic_attribute_names %>
  <% if dynamic_feilds.present? %>
    <% dynamic_feilds.each do |dynamic_feild|%>
      <%= s.label @recommend_recommend_other.dynamic_attribute_human(dynamic_feild) %>
      <%= s.value dynamic_feild%>
    <% end %>
  <% end %>
  <%= s.attribute :created_at %>
  <%= s.attribute :updated_at %>
<% end %>

<% if can? :update, @recommend_recommend_other %>
  <%= link_to t('.edit', :default => t("helpers.links.edit", :model => model_class.model_name.human)), edit_recommend_recommend_other_path(@recommend_recommend_other), :class => 'btn' %> |
<% end %>
<% if can? :read, @recommend_recommend_other %>
  <%= link_to t('.back', :default => t("helpers.links.back", :model => model_class.model_name.human)), recommend_recommend_others_path, :class => 'btn' %> |
<% end %>
<% if can? :destroy, @recommend_recommend_other %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy", :model => model_class.model_name.human)), recommend_recommend_other_path(@recommend_recommend_other),
              :method => 'delete',
              :confirm => t('.confirm',
              :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
<% end %>

app/views/recommend/recommend_others/update_field.js.erb
$("#recommend_recommend_other").replaceWith("<%= escape_javascript(render 'form') %>");