config/routes.rb
BBTangCMS::Application.routes.draw do

  namespace :admin do
    resources :base_settings, :include => [:index] do
      collection do
        match 'save'
        match 'add_report_reason'
        match 'delete_report_reason'
      end
    end

    resources :email_settings, :include => [:index] do
      collection do
        match 'save'
        match 'send_test_email'
      end
    end

    resources :code_settings

    resources :links_settings, :include => [:index] do
      collection do
        match 'new_link'
        match 'create_link'
        match 'edit_link'
        match 'update_link'
        match 'delete_link'
      end
    end

    resources :seo_settings

    resources :ip_settings do
      collection do
        post :save
      end
    end

  end

  resources :attachments

  namespace :auth do
    resources :users
    resources :cms_roles
    resources :assign_permits
    root :to => 'dashboard#show', :as => :dashboard
  end

  resources :messages, :only => [:new, :create] do
    collection do
      get 'token' => 'messages#token', :as => 'token'
      post 'empty/:messagebox' => 'messages#empty', :as => 'empty'
      put 'update' => 'messages#update'
      get ':messagebox/show/:id' => 'messages#show', :as => 'show', :constraints => { :messagebox => /inbox|outbox|trash/ }
      get '(/:messagebox)' => 'messages#index', :as => 'box', :constraints => { :messagebox => /inbox|outbox|trash/ }
    end
  end

  resources :notes, :except => [:new, :create]

  namespace :kindeditor do
    match '/upload' => 'assets#create', :via => :post
    match '/filemanager' => 'assets#list', :via => :get
  end

  resources :knowledges do
    member do
      get 'refresh'
    end
  end

  resources :profiles, :except => [:new, :create]
  resources :page_requests

  resources :questions do
    collection do
      get 'resetscore'
      match 'update_timelines'
      match 'update_categories'
    end
    resources :answers
  end

  namespace :quiz_center do
    resources :quizzes
    resources :quiz_collections
    root :to => 'quiz_collections#index', :as => :dashboard
  end

  namespace :recommend do
    resources :expert_categories
    resources :other_columns
    resources :recommend_apps
    resources :recommend_events
    resources :recommend_hindices
    resources :recommend_mtools
    resources :recommend_others do
      collection do
        match 'update_field'
      end
    end
    resources :recommend_quizzes
    resources :recommend_products
    resources :recommend_ptags
    resources :recommend_questions
    resources :recommend_subjects
    resources :recommend_tags
    resources :recommend_users
    resources :vip_categories
    root :to => 'dashboard#show', :as => :dashboard
  end
  
  resources :source_trackers do
    collection do
      match :query
    end
  end

  get "site/about"
  get "site/changelog"
  get "site/license"
  get "site/policies"
  get "site/team"
  get "site/support"

  namespace :tag do
    resources :identities , :only => [:index, :show, :new, :create] do
      resources :timelines, :only => [:index, :show, :new, :create] do
        resources :categories
      end
    end
    root :to => 'dashboard#show', :as => :dashboard
  end

  namespace :work do
    resources :analytics, only: [:index ] do
      collection do
        match :filter
      end
    end
    resources :versions, only: [:index, :show ]
    resources :user_statistics, only: [:index ] do
      collection do
        match :filter
      end
    end
    resources :contacts
    root :to => 'dashboard#show', :as => :dashboard
  end

  devise_for :users

  match "common/search", :as => :common_search
  match "common/lastest_log", :as => :common_lastest_log
  root :to => 'dashboard#index'
  match "/archives/hot_tags/" => "hot_tags#index", :as => :hot_tags, :via => :get
  match "/archives/:model/" => "archives#index", :as => :archives, :via => :get
  match "/archives/savesort" => 'archives#savesort'
  match "/archives/search_tag" => 'archives#search_tag', :as => :search_tag
  match '/archives/:model/item_list/:item_id/' => "archives#item_list", :as => :archive_item_list, :via => :get

  unless BBTangCMS::Application.config.consider_all_requests_local
    match '/403', :to => 'errors#render_403'
    match '/404', :to => 'errors#render_404'
    match '/422', :to => 'errors#render_422'
    match '/500', :to => 'errors#render_500'
  end

end

app/models/answer.rb
# coding: utf-8
class Answer < ActiveRecord::Base
  belongs_to :question
  has_paper_trail   # you can pass various options here

  validates :question_id, :presence => true
  validates :body, :presence => true#, :length => {:maximum => Askjane::MetaCache.get_config_data("answer_body_max").to_i}

  after_initialize :init

  before_validation :repear_save
  after_save :update_question

  #destroy associate event_log
  after_save :clear_event_log_and_notify
  after_destroy :clear_event_log_and_notify


  attr_accessor :soft_deleted
    attr_accessible :body, :created_by, :created_at, :state,
                  :updated_at, :is_anonymous, :soft_deleted, :is_expert

  # 设置初始值
  def init
    self.expert_count ||= 0
    self.thanks_count ||= 0
    self.is_anonymous ||= 0
  end

  def available_comments
    Comment.where(["model_object_id=? and object_target_id=? and deleted_at is null", 2,self.id])
  end

  def clear_event_log_and_notify
    #Eventlog.remove("item_id" => params[:id].to_i, "item_type"=>"Note")
    if (self.respond_to? :deleted_by and self.send(:deleted_by)) or not(self.class.exists? self.id)
      #EventLog.where(item_type: self.class.to_s,item_id: id).collect{|event_log| event_log.destroy} if self.present?
      Eventlog.remove("answer_id" => self.id , "item_type"=>"Answer")
      Notify.remove("item_id" => self.id , "item_type"=>self.class.name)
    end
  end

  # answer 的 owner
  def owner
    Profile.find_by_user_id(self.created_by)
  end

  def created_user
    User.find(self.created_by) if (self.created_by.present?) and (User.exists? self.created_by)
  end



  def repear_save
    self.content = Sanitize.clean(self.body).strip
  end

  def if_soft_deleted(soft_deleted =nil, user = nil)
    if soft_deleted.present? and user.present?
      if ["true","1",1,true].include? soft_deleted
        self.deleted_at = Time.now
        self.deleted_by = user.id if user.id.present?
      else
        self.deleted_at = nil
        self.deleted_by = nil
      end
    end
  end

  def deleted_user
    User.find(self.deleted_by) if (self.deleted_by.present?) and (User.exists? self.deleted_by)
  end

  def update_question
    if self.question_id.present? and Question.exists? self.question_id
      question = Question.find(self.question_id)
      question.answers_count = question.answers_count.to_i + 1
      question.save
    end
  end

  def to_s
    "#{self.id}"
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= simple_form_for([@question,@answer]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <!--%= f.input :content %-->
    <%= f.input :body, :as => :kindeditor %>
    <!--%= f.input :created_by %-->
    <!--%= f.input :question_id %-->
    <!--%= f.input :opposition_count %-->
    <!--%= f.input :opposition_ids %-->
    <!--%= f.input :approval_count %-->
    <!--%= f.input :approval_ids %-->
    <!--%= f.input :expert_count %-->
    <!--%= f.input :deleted_at %-->
    <!--%= f.input :deleted_by %-->
    <%= f.input :is_anonymous %>
    <!--%= f.input :no_help_count %-->
    <!--%= f.input :no_help_ids %-->
    <!--%= f.input :delta %-->
    <%= f.input :soft_deleted, :as => :boolean, :input_html => {:checked =>  @answer.deleted_at? ? "checked" : ""} %>
    <%= f.input :state %>
    <% if @answer.new_record? %>
      <%= f.input :created_by, :as => :hidden, :input_html => { :value => (current_user.id if current_user.present?) } %>
      <%= f.input :created_at, :as => :hidden, :input_html => { :value => Time.now } %>
    <% else %>
      <%= f.input :updated_at, :as => :hidden, :input_html => { :value => Time.now} %>
    <% end %>
    <%= f.input :is_expert %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                question_answers_path(@question), :class => 'btn' %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<%- model_class = @answer.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>

  <div class="mod_action btn-group">
    <button class="btn btn-primary"><%=t('.operate', :default => t("helpers.links.operate", :model => model_class.model_name.human)) %></button>
    <button data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li>
        <% if can? :create, Answer %>
          <%= link_to t('.new', :default => t("helpers.links.new", :model => model_class.model_name.human)),
                    new_question_answer_path(@question) %>
        <% end %>
      </li>
      <li>
        <% if can? :read, @answer %>
          <%= link_to t('.back', :default => t("helpers.links.back", :model => model_class.model_name.human)),
                    question_answers_path(@question)  %>
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
        <% if can? :destroy, @answer %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy", :model => model_class.model_name.human)),
                    [@question,@answer],
                    :method => 'delete',
                    :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) %>
        <% end %>
      </li>
    </ul>
  </div>
</div>
<%= render 'form' %>

app/views/answers/index.html.erb
<%- model_class = Answer.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>

  <div class="mod_action btn-group">
    <button class="btn btn-primary"><%=t('.operate', :default => t("helpers.links.operate", :model => model_class.model_name.human)) %></button>
    <button data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li>
        <% if can? :create, Answer %>
          <%= link_to t('.new', :default => t("helpers.links.new", :model => model_class.model_name.human)),
                    new_question_answer_path(@question) %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

<div class = "answers box">
<table class="table table-striped">
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <!--th><!--%= model_class.human_attribute_name(:content) %></th-->
    <!--th><!--%= model_class.human_attribute_name(:body) %></th-->
    <th><%= model_class.human_attribute_name(:created_user) %></th>
    <th><%= model_class.human_attribute_name(:question_id) %></th>
    <th><%= model_class.human_attribute_name(:opposition_count) %></th>
    <!--th><!--%= model_class.human_attribute_name(:opposition_ids) %></th-->
    <th><%= model_class.human_attribute_name(:approval_count) %></th>
    <!--th><!--%= model_class.human_attribute_name(:approval_ids) %></th-->
    <th><%= model_class.human_attribute_name(:experts_count) %></th>
    <th><%= model_class.human_attribute_name(:deleted_at) %></th>
    <th><%= model_class.human_attribute_name(:deleted_user) %></th>
    <th><%= model_class.human_attribute_name(:is_anonymous) %></th>
    <th><%= model_class.human_attribute_name(:no_help_count) %></th>
    <!--th><!--%= model_class.human_attribute_name(:no_help_ids) %></th-->
    <!--th><!--%= model_class.human_attribute_name(:delta) %></th-->
    <th><%= model_class.human_attribute_name(:state) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%= model_class.human_attribute_name(:updated_a) %></th>
    <th><%= model_class.human_attribute_name(:is_expert) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<%- indicates = true %>
<% @answers.each do |answer| %>
  <tr class=<%= (indicates =!indicates) ? "success" : "info"%>>
    <td><%= answer.id %></td>
    <!--td><!--%= answer.content %></td-->
    <!--td><!--%= answer.body %></td-->
    <td><%= answer.created_user %></td>
    <td><%= link_to answer.question_id, question_path(answer.question_id) if answer.question_id.present? %></td>
    <td><%= answer.opposition_count %></td>
    <!--td><!--%= answer.opposition_ids %></td-->
    <td><%= answer.approval_count %></td>
    <!--td><!--%= answer.approval_ids %></td-->
    <td><%= answer.expert_count %></td>
    <td><%= answer.deleted_at %></td>
    <td><%= answer.deleted_user %></td>
    <td><%= answer.is_anonymous %></td>
    <td><%= answer.no_help_count %></td>
    <!--td><!--%= answer.no_help_ids %></td-->
    <!--td><!--%= answer.delta %></td-->
    <td><%= answer.state %></td>
    <td><%= answer.created_at %></td>
    <td><%= answer.updated_at %></td>
    <td><%= answer.is_expert %></td>
    <td>
          <%= link_to t('.show', :default => t("helpers.links.show", :model => model_class.model_name.human)),
                      question_answer_path(@question,answer),
                      :class => 'btn btn-mini',
                      :title => "#{t("helpers.links.show", :model => model_class.model_name.human)} #{answer}",
                      "data-content" => object_summary(obj = answer, column = "content"),
                       :rel => "popover"
                       %>
          <% if can? :update, answer %>
            <%= link_to t('.edit', :default => t("helpers.links.edit", :model => model_class.model_name.human)),
                      edit_question_answer_path(@question,answer),
                      :class => 'btn btn-mini',
                      :title => "#{t("helpers.links.edit", :model => model_class.model_name.human)} #{answer}",
                      "data-content" => object_summary(obj = answer, column = "content"),
                       :rel => "popover"
                       %>
          <% end %>
          <% if can? :destroy, answer %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy", :model => model_class.model_name.human)),
                      question_answer_path(@question,answer),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
          <% end %>

  </tr>
<% end %>
</table>

<br />

<% if can? :create, Answer %>
  <%= link_to t('.new', :default => t("helpers.links.new", :model => model_class.model_name.human)),
            new_question_answer_path(@question),
            :class => 'btn btn-primary' %>
<% end %>
</div>

app/views/answers/new.html.erb
<%- model_class = @answer.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render 'form' %>

app/views/answers/show.html.erb
<%- model_class = @answer.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.show', :model => model_class.model_name.human) %></h1>

  <div class="mod_action btn-group">
    <button class="btn btn-primary"><%=t('.operate', :default => t("helpers.links.operate", :model => model_class.model_name.human)) %></button>
    <button data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li>
        <% if can? :create, Answer %>
          <%= link_to t('.new', :default => t("helpers.links.new", :model => model_class.model_name.human)),
                    new_question_answer_path(@question) %>
        <% end %>
      </li>
      <li>
        <% if can? :read, @answer %>
          <%= link_to t('.back', :default => t("helpers.links.back", :model => model_class.model_name.human)),
                    question_answers_path(@question)  %>
        <% end %>
      </li>
      <li>
        <% if can? :update, @answer %>
          <%= link_to t('.edit', :default => t("helpers.links.edit", :model => model_class.model_name.human)),
                    edit_question_answer_path(@question,@answer) %>
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
        <% if can? :destroy, @answer %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy", :model => model_class.model_name.human)),
                    [@question,@answer],
                    :method => 'delete',
                    :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) %>
        <% end %>
      </li>
    </ul>
  </div>
</div>


<%= show_for @answer do |s| %>
  <!--%= s.attribute :content %-->
  <%= s.attribute :body, :value => (raw @answer.body) %>
  <%= s.attribute :created_by %>
  <%= s.attribute :question_id %>
  <%= s.attribute :opposition_count %>
  <%= s.attribute :opposition_ids %>
  <%= s.attribute :approval_count %>
  <%= s.attribute :approval_ids %>
  <%= s.attribute :expert_count %>
  <%= s.attribute :deleted_at %>
  <%= s.attribute :deleted_user %>
  <%= s.attribute :is_anonymous %>
  <%= s.attribute :no_help_count %>
  <%= s.attribute :no_help_ids %>
  <%= s.attribute :delta %>
  <%= s.attribute :state %>
  <%= s.attribute :created_at %>
  <%= s.attribute :updated_at %>
  <%= s.attribute :is_expert %>
<% end %>

<div class="actions">
  <% if can? :read, @answer %>
    <%= link_to t('.back', :default => t("helpers.links.back", :model => model_class.model_name.human)),
              question_answers_path(@question), :class => 'btn'  %>
  <% end %>
  <% if can? :update, @answer %>
    <%= link_to t('.edit', :default => t("helpers.links.edit", :model => model_class.model_name.human)),
              edit_question_answer_path(@question,@answer), :class => 'btn' %>
  <% end %>
  <% if can? :destroy, @answer %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy", :model => model_class.model_name.human)),
              [@question,@answer],
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
  <% end %>
</div>