config/routes.rb
BBTangCMS::Application.routes.draw do

  namespace :admin do
    resources :base_settings, :include => [:index] do
      collection do
        match 'save'
        match 'add_report_reason'
        match 'delete_report_reason'
      end
    end

    resources :email_settings, :include => [:index] do
      collection do
        match 'save'
        match 'send_test_email'
      end
    end

    resources :code_settings

    resources :links_settings, :include => [:index] do
      collection do
        match 'new_link'
        match 'create_link'
        match 'edit_link'
        match 'update_link'
        match 'delete_link'
      end
    end

    resources :seo_settings

    resources :ip_settings do
      collection do
        post :save
      end
    end

  end

  resources :attachments

  namespace :auth do
    resources :users
    resources :cms_roles
    resources :assign_permits
    root :to => 'dashboard#show', :as => :dashboard
  end

  resources :messages, :only => [:new, :create] do
    collection do
      get 'token' => 'messages#token', :as => 'token'
      post 'empty/:messagebox' => 'messages#empty', :as => 'empty'
      put 'update' => 'messages#update'
      get ':messagebox/show/:id' => 'messages#show', :as => 'show', :constraints => { :messagebox => /inbox|outbox|trash/ }
      get '(/:messagebox)' => 'messages#index', :as => 'box', :constraints => { :messagebox => /inbox|outbox|trash/ }
    end
  end

  resources :notes, :except => [:new, :create]

  namespace :kindeditor do
    match '/upload' => 'assets#create', :via => :post
    match '/filemanager' => 'assets#list', :via => :get
  end

  resources :knowledges do
    member do
      get 'refresh'
    end
  end

  resources :profiles, :except => [:new, :create]
  resources :page_requests

  resources :questions do
    collection do
      get 'resetscore'
      match 'update_timelines'
      match 'update_categories'
    end
    resources :answers
  end

  namespace :quiz_center do
    resources :quizzes
    resources :quiz_collections
    root :to => 'quiz_collections#index', :as => :dashboard
  end

  namespace :recommend do
    resources :expert_categories
    resources :other_columns
    resources :recommend_apps
    resources :recommend_events
    resources :recommend_hindices
    resources :recommend_mtools
    resources :recommend_others do
      collection do
        match 'update_field'
      end
    end
    resources :recommend_quizzes
    resources :recommend_products
    resources :recommend_ptags
    resources :recommend_questions
    resources :recommend_subjects
    resources :recommend_tags
    resources :recommend_users
    resources :vip_categories
    root :to => 'dashboard#show', :as => :dashboard
  end
  
  resources :source_trackers do
    collection do
      match :query
    end
  end

  get "site/about"
  get "site/changelog"
  get "site/license"
  get "site/policies"
  get "site/team"
  get "site/support"

  namespace :tag do
    resources :identities , :only => [:index, :show, :new, :create] do
      resources :timelines, :only => [:index, :show, :new, :create] do
        resources :categories
      end
    end
    root :to => 'dashboard#show', :as => :dashboard
  end

  namespace :work do
    resources :analytics, only: [:index ] do
      collection do
        match :filter
      end
    end
    resources :versions, only: [:index, :show ]
    resources :user_statistics, only: [:index ] do
      collection do
        match :filter
      end
    end
    resources :contacts
    root :to => 'dashboard#show', :as => :dashboard
  end

  devise_for :users

  match "common/search", :as => :common_search
  match "common/lastest_log", :as => :common_lastest_log
  root :to => 'dashboard#index'
  match "/archives/hot_tags/" => "hot_tags#index", :as => :hot_tags, :via => :get
  match "/archives/:model/" => "archives#index", :as => :archives, :via => :get
  match "/archives/savesort" => 'archives#savesort'
  match "/archives/search_tag" => 'archives#search_tag', :as => :search_tag
  match '/archives/:model/item_list/:item_id/' => "archives#item_list", :as => :archive_item_list, :via => :get

  unless BBTangCMS::Application.config.consider_all_requests_local
    match '/403', :to => 'errors#render_403'
    match '/404', :to => 'errors#render_404'
    match '/422', :to => 'errors#render_422'
    match '/500', :to => 'errors#render_500'
  end

end

app/models/identity.rb
class Identity < CategoryBase
  has_paper_trail   # you can pass various options here
  validates :name, :presence => true, :uniqueness => true
  #def timelines
  #  self.children
  #end
end

app/controllers/tag/categories_controller.rb
class Tag::CategoriesController < Tag::TagBaseController
  load_and_authorize_resource
  #load_and_authorize_resource :identity
  #load_and_authorize_resource :timeline
  #load_resource :identity
  #load_resource :timeline
  #load_and_authorize_resource :category, :through => [:timeline], :shallow => true
  Model_class = Category.new.class
  before_filter :load_parent

  # GET /tag/categories
  # GET /tag/categories.json
  def index
    #@tag_categories = Category.all
    @tag_categories = @timeline.children.paginate(:page => params[:page]).order('id DESC')

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), tag_identity_timeline_categories_path(@identity,@timeline)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tag_categories }
    end
  end

  # GET /tag/categories/1
  # GET /tag/categories/1.json
  def show
    @tag_category = Category.find(params[:id])

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), tag_identity_timeline_category_path(@identity,@timeline,@tag_category)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag_category }
    end
  end

  # GET /tag/categories/new
  # GET /tag/categories/new.json
  def new
    #@tag_category = @timeline.children.new
    @tag_category = Category.new()

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), new_tag_identity_timeline_category_path(@identity,@timeline)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag_category }
    end
  end

  # GET /tag/categories/1/edit
  def edit
    @tag_category = Category.find(params[:id])
  end

  # POST /tag/categories
  # POST /tag/categories.json
  def create
    @tag_category = Category.new(params[:category])
    @tag_category.parent_id = @timeline.id if @timeline.present?

    respond_to do |format|
      if @tag_category.save
        format.html { redirect_to tag_identity_timeline_category_path(@identity,@timeline,@tag_category), notice: 'Category was successfully created.' }
        format.json { render json: @tag_category, status: :created, location: @tag_category }
      else
        format.html { render action: "new" }
        format.json { render json: @tag_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tag/categories/1
  # PUT /tag/categories/1.json
  def update
    @tag_category = Category.find(params[:id])
    @tag_category.parent_id = @timeline.id if @timeline.present?

    respond_to do |format|
      if @tag_category.update_attributes(params[:category])
        format.html { redirect_to tag_identity_timeline_category_path(@identity,@timeline,@tag_category), notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tag/categories/1
  # DELETE /tag/categories/1.json
  def destroy
    @tag_category = Category.find(params[:id])
    @tag_category.destroy

    respond_to do |format|
      format.html { redirect_to tag_identity_timeline_categories_url(@identity,@timeline) }
      format.json { head :no_content }
    end
  end

    def load_parent

      @identity = Identity.find(params[:identity_id])
      @timeline = Timeline.find(params[:timeline_id])
    end
end

app/controllers/tag/dashboard_controller.rb
class Tag::DashboardController < Tag::TagBaseController
  authorize_resource :class => false
  def show
    @root_tags = Identity.all
  end
end

app/controllers/tag/identities_controller.rb
class Tag::IdentitiesController < Tag::TagBaseController
  load_and_authorize_resource
  Model_class = Identity.new.class
  # GET /tag/identities
  # GET /tag/identities.json
  def index
    @tag_identities = Identity.all

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), tag_identities_path

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tag_identities }
    end
  end

  # GET /tag/identities/1
  # GET /tag/identities/1.json
  def show
    @tag_identity = Identity.find(params[:id])

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), tag_identity_path(@tag_identity)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag_identity }
    end
  end

  # GET /tag/identities/new
  # GET /tag/identities/new.json
  def new
    @tag_identity = Identity.new

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), new_tag_identity_path

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag_identity }
    end
  end

  # GET /tag/identities/1/edit
  def edit
    @tag_identity = Identity.find(params[:id])
  end

  # POST /tag/identities
  # POST /tag/identities.json
  def create
    @tag_identity = Identity.new(params[:identity])

    respond_to do |format|
      if @tag_identity.save
        format.html { redirect_to tag_identity_path(@tag_identity), notice: 'Identity was successfully created.' }
        format.json { render json: @tag_identity, status: :created, location: @tag_identity }
      else
        format.html { render action: "new" }
        format.json { render json: @tag_identity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tag/identities/1
  # PUT /tag/identities/1.json
  def update
    @tag_identity = Identity.find(params[:id])

    respond_to do |format|
      if @tag_identity.update_attributes(params[:identity])
        format.html { redirect_to @tag_identity, notice: 'Identity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag_identity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tag/identities/1
  # DELETE /tag/identities/1.json
  def destroy
    @tag_identity = Identity.find(params[:id])
    @tag_identity.destroy

    respond_to do |format|
      format.html { redirect_to tag_identities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tag/tag_base_controller.rb
class Tag::TagBaseController < ApplicationController
  after_filter :add_initial_breadcrumbs


  #before_filter :require_login
  protected

  def require_login
    return redirect_to(admin_session_path) unless session[:logged_in]
  end

  def set_content_type
    headers['Content-Type'] ||= 'text/html; charset=utf-8'
  end
  private
  def add_initial_breadcrumbs
    breadcrumbs.add :homepage, root_path
    #breadcrumbs.add :recommend, recommend_dashboard_path
    breadcrumbs.add ".namespace.tag", tag_dashboard_path
  end
end

app/controllers/tag/timelines_controller.rb
class Tag::TimelinesController < Tag::TagBaseController
  load_and_authorize_resource
  #load_resource :identity
  #load_and_authorize_resource :timeline, :through => [:identity], :shallow => true
  #load_and_authorize_resource :nested => :identity
  Model_class = Timeline.new.class
  before_filter :load_parent

  # GET /tag/timelines
  # GET /tag/timelines.json
  def index
    #@tag_timelines = Timeline.all
    @tag_timelines = @identity.children.paginate(:page => params[:page]).order('id DESC')

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), tag_identity_timelines_path(@identity)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tag_timelines }
    end
  end

  # GET /tag/timelines/1
  # GET /tag/timelines/1.json
  def show
    @tag_timeline = Timeline.find(params[:id])

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), tag_identity_timeline_path(@identity,@tag_timeline)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag_timeline }
    end
  end

  # GET /tag/timelines/new
  # GET /tag/timelines/new.json
  def new
    #@tag_timeline = @identity.children.new
    @tag_timeline = Timeline.new(parent_id: @identity.id)

    breadcrumbs.add I18n.t("helpers.titles.#{current_action}", :model => Model_class.model_name.human), new_tag_identity_timeline_path(@identity)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag_timeline }
    end
  end

  # GET /tag/timelines/1/edit
  def edit
    @tag_timeline = Timeline.find(params[:id])
  end

  # POST /tag/timelines
  # POST /tag/timelines.json
  def create
    @tag_timeline = Timeline.new(params[:timeline])
    @tag_timeline.parent_id = @identity.id if @identity.present?

    respond_to do |format|
      if @tag_timeline.save
        format.html { redirect_to tag_identity_timeline_path(@identity,@tag_timeline), notice: 'Timeline was successfully created.' }
        format.json { render json: @tag_timeline, status: :created, location: @tag_timeline }
      else
        format.html { render action: "new" }
        format.json { render json: @tag_timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tag/timelines/1
  # PUT /tag/timelines/1.json
  def update
    @tag_timeline = Timeline.find(params[:id])
    @tag_timeline.parent_id = @identity.id if @identity.present?

    respond_to do |format|
      if @tag_timeline.update_attributes(params[:timeline])
        format.html { redirect_to @tag_timeline, notice: 'Timeline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag_timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tag/timelines/1
  # DELETE /tag/timelines/1.json
  def destroy
    @tag_timeline = Timeline.find(params[:id])
    @tag_timeline.destroy

    respond_to do |format|
      format.html { redirect_to tag_timelines_url }
      format.json { head :no_content }
    end
  end
  private

    def load_parent

      @identity = Identity.find(params[:identity_id])
    end
end

app/helpers/tag/categories_helper.rb
module Tag::CategoriesHelper
end

app/helpers/tag/identities_helper.rb
module Tag::IdentitiesHelper
end

app/helpers/tag/timelines_helper.rb
module Tag::TimelinesHelper
end

app/views/tag/identities/_form.html.erb
<%= simple_form_for([:tag,@tag_identity]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <!--%= f.input :parent_id %-->
    <!--%= f.input :created_at %-->
    <!--%= f.input :updated_at %-->
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary', :disable_with => 'loading...' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tag_identities_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tag/identities/edit.html.erb
<h1>Editing tag_identity</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag_identity %> |
<%= link_to 'Back', tag_identities_path %>

app/views/tag/identities/index.html.erb
<%- model_class = Identity.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<div class = "identities box">
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:parent) %></th>
      <th><%= model_class.human_attribute_name(:children) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

  <tbody>
<%- indicates = true %>
<% @tag_identities.each do |tag_identity| %>
  <tr class=<%= (indicates =!indicates) ? "success" : "info"%>>
    <td><%= link_to tag_identity.id, tag_identity_path(tag_identity) %></td>
    <td><%= tag_identity.name %></td>
    <td><%= link_to tag_identity.parent_id if tag_identity.parent_id.present? %></td>
    <td><%= link_to tag_identity.children.count, tag_identity_timelines_path(tag_identity) if tag_identity.children.present? %></td>
    <td><%=time_tag tag_identity.created_at, :format => :default if tag_identity.created_at?    %></td>
    <td><%=time_tag tag_identity.updated_at, :format => :default if tag_identity.updated_at?    %></td>
    <td><%= link_to t('.show', :default => t("helpers.links.show", :model => model_class.model_name.human)),
                      tag_identity_path(tag_identity), :class => 'btn btn-mini' %></td>
    <!--td><!--%= link_to 'Edit', edit_tag_identity_path(tag_identity) %></td-->
    <!--td><!--%= link_to 'Destroy', tag_identity, confirm: 'Are you sure?', method: :delete %></td-->
  </tr>
<% end %>
  </tbody>
</table>

<br />

<% if can? :create, Identity %>
  <%= link_to t('.new', :default => t("helpers.links.new", :model => model_class.model_name.human)),
        new_tag_identity_path,
        :class => 'btn btn-primary'  %>
<% end %>
</div>

app/views/tag/identities/new.html.erb
<%- model_class = @tag_identity.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render 'form' %>

app/views/tag/identities/show.html.erb
<%- model_class = @identity.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.show', :model => model_class.model_name.human) %></h1>
</div>

<%= show_for @identity do |s| %>
  <%= s.attribute :name %>
  <%= s.attribute :parent %>
  <%= s.attribute :children %>
  <%= s.attribute :description %>
  <%= s.attribute :created_at %>
  <%= s.attribute :updated_at %>
<% end %>

<div class="actions">
  <!--%= link_to 'Edit', edit_tag_identity_path(@identity) %-->
  <% if can? :read, @identity.class %>
    <%= link_to t('.back', :default => t("helpers.links.back", :model => model_class.model_name.human)),
              tag_identities_path, :class => 'btn'  %>
  <% end %>
</div>